### ISSUE TITLE
table jump note

### ISSUE THREAD

**Issue by linsinan1995** [linsinan1995/riscv-binutils-gdb#8]
# Road Map
- [x] profiling
- [x] tbljal insn codegen
- [x] objdump insn with notation (function name & address) 
- [x] write tbljal entries into executable file
- [x] csr and its initialization
- [x] compiler switch
- [ ] testcases

# implementation idea

# test case
test.c
```c
int foo1();
static int foo() {return 2 + foo1();};
int main() {
  asm goto (
        "jal x0,%l[end]"
        :
        :
        :
        : end
    );
end:
  return foo() + foo1();
}
```

wow.c
```c
int foo1() {return 1;}
```

`riscv64-unknown-elf-gcc -mzce-tbljal  -msave-restore  test.c wow.c -O1`

# Dumped infos by steps
## 1. Record address and size saving in a hash table
```
name=memset, address=102d8, benefit=2
name=atexit, address=10480, benefit=2
name=__libc_init_array, address=10266, benefit=2
name=main, address=10194, benefit=2
name=__riscv_save_1, address=1020a, benefit=2
name=foo1, address=101be, benefit=2
name=foo1, address=101be, benefit=2
name=.L2, address=101a0, benefit=2
name=__call_exitprocs, address=10382, benefit=2
name=_exit, address=1050a, benefit=2
name=__errno, address=10530, benefit=2
name=memset, address=102d8, benefit=2
name=atexit, address=10480, benefit=2
name=__libc_init_array, address=10266, benefit=2
name=main, address=10194, benefit=2
name=__riscv_save_1, address=1020a, benefit=2
name=foo1, address=101be, benefit=2
name=foo1, address=101be, benefit=2
name=.L2, address=101a0, benefit=2
name=__call_exitprocs, address=10382, benefit=2
name=_exit, address=1050a, benefit=2
name=__errno, address=10530, benefit=2
```

## 2. Profile and build table jump entries
N.B. they are not the final address. 
```
tbjalm:
	index=0, sym name=__riscv_save_1, address=0x0001020a, benefits=4
tbj:
	index=8, sym name=.L2, address=0x000101a0, benefits=4
tbjal:
	index=64, sym name=foo1, address=0x000101be, benefits=8
	index=65, sym name=__libc_init_array, address=0x00010266, benefits=4
	index=66, sym name=__call_exitprocs, address=0x00010382, benefits=4
	index=67, sym name=memset, address=0x000102d8, benefits=4
	index=68, sym name=main, address=0x00010194, benefits=4
	index=69, sym name=atexit, address=0x00010480, benefits=4
	index=70, sym name=_exit, address=0x0001050a, benefits=4
	index=71, sym name=__errno, address=0x00010530, benefits=4
```

## 3. Update table jump entries after relocation
```c
tbjalm:
	index=0, sym name=__riscv_save_1, address=0x000101ac, benefits=4
tbj:
	index=8, sym name=.L2, address=0x000101a0, benefits=4
tbjal:
	index=64, sym name=foo1, address=0x00010160, benefits=8
	index=65, sym name=__libc_init_array, address=0x000101f8, benefits=4
	index=66, sym name=__call_exitprocs, address=0x0001030c, benefits=4
	index=67, sym name=memset, address=0x00010262, benefits=4
	index=68, sym name=main, address=0x0001014e, benefits=4
	index=69, sym name=atexit, address=0x00010402, benefits=4
	index=70, sym name=_exit, address=0x00010482, benefits=4
	index=71, sym name=__errno, address=0x000104a2, benefits=4
```

## 4. CSR initialization
symbol for initializing csr
```
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-readelf -s a.out | grep __tbljalvec_base
  82: 00000000000104a8     0 NOTYPE  GLOBAL DEFAULT    2 __tbljalvec_base$
```

```
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-objdump -dr a.out | grep __tbljalvec_base -A 1
   100cc:	3e050513          	addi	a0,a0,992 # 104a8 <__tbljalvec_base$>
   100d0:	80051073          	csrw	0x800,a0
```

# Other Info
## Machine code comparison
compile without table jump option
```asm
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-objdump -dr a.out | grep "main>:" -A 12
000000000001014a <main>:
   1014a:	064002ef          	jal	t0,101ae <__riscv_save_0>
   1014e:	0040006f          	j	10152 <main+0x8>
   10152:	010000ef          	jal	ra,10162 <foo1>
   10156:	842a                	mv	s0,a0
   10158:	00a000ef          	jal	ra,10162 <foo1>
   1015c:	2409                	addiw	s0,s0,2
   1015e:	9d21                	addw	a0,a0,s0
   10160:	a8a5                	j	101d8 <__riscv_restore_0>

0000000000010162 <foo1>:
   10162:	4505                	li	a0,1
   10164:	8082                	ret
```

compile with table jump option
```asm
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-objdump -dr a.out | grep main -A 10
000000000001014e <main>:
   1014e:	8800                	c.tbljalm	0
   10150:	0040006f          	j	10154 <main+0x6>
   10154:	8900                	c.tbljal	64
   10156:	842a                	mv	s0,a0
   10158:	8900                	c.tbljal	64
   1015a:	2409                	addiw	s0,s0,2
   1015c:	9d21                	addw	a0,a0,s0
   1015e:	a8a5                	j	101d6 <__riscv_restore_0>

0000000000010160 <foo1>:
   10160:	4505                	li	a0,1
   10162:	8082                	ret
```

## symbol table (function type symbol) in a.out
```
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-readelf -s a.out |  grep FUNC
    17: 00000000000100b0    16 FUNC    LOCAL  DEFAULT    1 register_fini
    20: 0000000000010102     0 FUNC    LOCAL  DEFAULT    1 __do_global_dtors_aux
    23: 0000000000010134     0 FUNC    LOCAL  DEFAULT    1 frame_dummy
    47: 0000000000010176    54 FUNC    GLOBAL HIDDEN     1 __riscv_save_8
    48: 00000000000101d0    14 FUNC    GLOBAL HIDDEN     1 __riscv_restore_3
    49: 00000000000101b8    38 FUNC    GLOBAL HIDDEN     1 __riscv_restore_10
    50: 000000000001016c    64 FUNC    GLOBAL HIDDEN     1 __riscv_save_11
    51: 00000000000104a2     6 FUNC    GLOBAL DEFAULT    1 __errno
    53: 00000000000101d0    14 FUNC    GLOBAL HIDDEN     1 __riscv_restore_2
    54: 0000000000010164    72 FUNC    GLOBAL HIDDEN     1 __riscv_save_12
    56: 00000000000101b8    38 FUNC    GLOBAL HIDDEN     1 __riscv_restore_11
    57: 00000000000101ac     8 FUNC    GLOBAL HIDDEN     1 __riscv_save_1
    58: 00000000000101d6     8 FUNC    GLOBAL HIDDEN     1 __riscv_restore_0
    59: 0000000000010180    44 FUNC    GLOBAL HIDDEN     1 __riscv_save_7
    61: 00000000000101ca    20 FUNC    GLOBAL HIDDEN     1 __riscv_restore_5
    62: 00000000000101f8   106 FUNC    GLOBAL DEFAULT    1 __libc_init_array
    63: 00000000000101c4    26 FUNC    GLOBAL HIDDEN     1 __riscv_restore_6
    64: 00000000000103ce    52 FUNC    GLOBAL DEFAULT    1 __libc_fini_array
    65: 0000000000010176    54 FUNC    GLOBAL HIDDEN     1 __riscv_save_9
    66: 0000000000010160     4 FUNC    GLOBAL DEFAULT    1 foo1
    67: 000000000001018c    32 FUNC    GLOBAL HIDDEN     1 __riscv_save_4
    68: 0000000000010198    20 FUNC    GLOBAL HIDDEN     1 __riscv_save_3
    69: 000000000001030c   194 FUNC    GLOBAL DEFAULT    1 __call_exitprocs
    70: 00000000000100c0    66 FUNC    GLOBAL DEFAULT    1 _start
    71: 000000000001040c   118 FUNC    GLOBAL DEFAULT    1 __register_exitproc
    73: 000000000001016c    64 FUNC    GLOBAL HIDDEN     1 __riscv_save_10
    74: 00000000000101ca    20 FUNC    GLOBAL HIDDEN     1 __riscv_restore_4
    75: 00000000000101be    32 FUNC    GLOBAL HIDDEN     1 __riscv_restore_8
    76: 0000000000010180    44 FUNC    GLOBAL HIDDEN     1 __riscv_save_6
    78: 0000000000010262   170 FUNC    GLOBAL DEFAULT    1 memset
    79: 00000000000101be    32 FUNC    GLOBAL HIDDEN     1 __riscv_restore_9
    80: 00000000000101c4    26 FUNC    GLOBAL HIDDEN     1 __riscv_restore_7
    81: 000000000001014e    18 FUNC    GLOBAL DEFAULT    1 main
    83: 0000000000010402    10 FUNC    GLOBAL DEFAULT    1 atexit
    85: 0000000000010198    20 FUNC    GLOBAL HIDDEN     1 __riscv_save_2
    87: 000000000001018c    32 FUNC    GLOBAL HIDDEN     1 __riscv_save_5
    90: 00000000000101de    26 FUNC    GLOBAL DEFAULT    1 exit
    91: 00000000000101b4    42 FUNC    GLOBAL HIDDEN     1 __riscv_restore_12
    92: 00000000000101ac     8 FUNC    GLOBAL HIDDEN     1 __riscv_save_0
    93: 0000000000010482    32 FUNC    GLOBAL DEFAULT    1 _exit
    94: 00000000000101d6     8 FUNC    GLOBAL HIDDEN     1 __riscv_restore_1
```

## Section headers
```
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-readelf -S a.out
There are 19 section headers, starting at offset 0x29b0:

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .text             PROGBITS         00000000000100b0  000000b0
       00000000000003f8  0000000000000000  AX       0     0     2
  [ 2] .tbljal           PROGBITS         00000000000104a8  000004a8
       0000000000000800  0000000000000000   A       0     0     1
  [ 3] .eh_frame         PROGBITS         0000000000011000  00001000
       0000000000000138  0000000000000000  WA       0     0     8
  [ 4] .init_array       INIT_ARRAY       0000000000011138  00001138
       0000000000000010  0000000000000008  WA       0     0     8
  [ 5] .fini_array       FINI_ARRAY       0000000000011148  00001148
       0000000000000008  0000000000000008  WA       0     0     8
  [ 6] .data             PROGBITS         0000000000011150  00001150
       0000000000000748  0000000000000000  WA       0     0     8
  [ 7] .sdata            PROGBITS         0000000000011898  00001898
       0000000000000018  0000000000000000  WA       0     0     8
  [ 8] .bss              NOBITS           00000000000118b0  000018b0
       0000000000000038  0000000000000000  WA       0     0     8
  [ 9] .comment          PROGBITS         0000000000000000  000018b0
       0000000000000012  0000000000000001  MS       0     0     1
  [10] .riscv.attributes RISCV_ATTRIBUTE  0000000000000000  000018c2
       0000000000000043  0000000000000000           0     0     1
  [11] .debug_aranges    PROGBITS         0000000000000000  00001910
       0000000000000030  0000000000000000           0     0     16
  [12] .debug_info       PROGBITS         0000000000000000  00001940
       000000000000002e  0000000000000000           0     0     1
  [13] .debug_abbrev     PROGBITS         0000000000000000  0000196e
       0000000000000014  0000000000000000           0     0     1
  [14] .debug_line       PROGBITS         0000000000000000  00001982
       00000000000001bc  0000000000000000           0     0     1
  [15] .debug_str        PROGBITS         0000000000000000  00001b3e
       000000000000009e  0000000000000001  MS       0     0     1
  [16] .symtab           SYMTAB           0000000000000000  00001be0
       00000000000008e8  0000000000000018          17    46     8
  [17] .strtab           STRTAB           0000000000000000  000024c8
       000000000000042c  0000000000000000           0     0     1
  [18] .shstrtab         STRTAB           0000000000000000  000028f4
       00000000000000b8  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)
```

## Hex info in .tbljal section
objdump for .tbljal section
```
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-objdump -s -j .tbljal a.out

a.out:     file format elf64-littleriscv

Contents of section .tbljal:
 104a8 ac010100 00000000 00000000 00000000  ................
 104b8 00000000 00000000 00000000 00000000  ................
 104c8 00000000 00000000 00000000 00000000  ................
 104d8 00000000 00000000 00000000 00000000  ................
 104e8 a0010100 00000000 00000000 00000000  ................
 104f8 00000000 00000000 00000000 00000000  ................
 10508 00000000 00000000 00000000 00000000  ................
 10518 00000000 00000000 00000000 00000000  ................
 10528 00000000 00000000 00000000 00000000  ................
 10538 00000000 00000000 00000000 00000000  ................
 10548 00000000 00000000 00000000 00000000  ................
 10558 00000000 00000000 00000000 00000000  ................
 10568 00000000 00000000 00000000 00000000  ................
 10578 00000000 00000000 00000000 00000000  ................
 10588 00000000 00000000 00000000 00000000  ................
 10598 00000000 00000000 00000000 00000000  ................
 105a8 00000000 00000000 00000000 00000000  ................
 105b8 00000000 00000000 00000000 00000000  ................
 105c8 00000000 00000000 00000000 00000000  ................
 105d8 00000000 00000000 00000000 00000000  ................
 105e8 00000000 00000000 00000000 00000000  ................
 105f8 00000000 00000000 00000000 00000000  ................
 10608 00000000 00000000 00000000 00000000  ................
 10618 00000000 00000000 00000000 00000000  ................
 10628 00000000 00000000 00000000 00000000  ................
 10638 00000000 00000000 00000000 00000000  ................
 10648 00000000 00000000 00000000 00000000  ................
 10658 00000000 00000000 00000000 00000000  ................
 10668 00000000 00000000 00000000 00000000  ................
 10678 00000000 00000000 00000000 00000000  ................
 10688 00000000 00000000 00000000 00000000  ................
 10698 00000000 00000000 00000000 00000000  ................
 106a8 60010100 00000000 f8010100 00000000  `...............
 106b8 0c030100 00000000 62020100 00000000  ........b.......
 106c8 4e010100 00000000 02040100 00000000  N...............
 106d8 82040100 00000000 a2040100 00000000  ................
 106e8 00000000 00000000 00000000 00000000  ................
```
then you can find the value of the first c.tbljalm entry(index 0) is 0x101ac, which is the address of `__riscv_save_1`.

**Comment by linsinan1995** [comment]
objdump without table jump
```
000000000001014a <main>:
   1014a:	060002ef          	jal	t0,101aa <__riscv_save_0>
   1014e:	010000ef          	jal	ra,1015e <wow>
   10152:	842a                	mv	s0,a0
   10154:	00a000ef          	jal	ra,1015e <wow>
   10158:	2409                	addiw	s0,s0,2
   1015a:	9d21                	addw	a0,a0,s0
   1015c:	a8a5                	j	101d4 <__riscv_restore_0>

000000000001015e <wow>:
   1015e:	4505                	li	a0,1
   10160:	8082                	ret
```

objdump with table jump
```
000000000001017a <main>:
   1017a:	8800                	c.tbljalm	0
   1017c:	8900                	c.tbljal	64
   1017e:	842a                	mv	s0,a0
   10180:	8900                	c.tbljal	64
   10182:	2409                	addiw	s0,s0,2
   10184:	9d21                	addw	a0,a0,s0
   10186:	a8a5                	j	101fe <__riscv_restore_0>

0000000000010188 <wow>:
   10188:	4505                	li	a0,1
   1018a:	8082                	ret
```

**Comment by linsinan1995** [comment]
objdump for .tbljal section
![image](https://user-images.githubusercontent.com/47880367/150094018-8575a028-70c2-479a-9ac8-fce63dd66115.png)

**Comment by linsinan1995** [comment]
change in newlib

```diff
diff --git a/libgloss/riscv/crt0.S b/libgloss/riscv/crt0.S
index 160c07853..46edd5469 100644
--- a/libgloss/riscv/crt0.S
+++ b/libgloss/riscv/crt0.S
@@ -26,6 +26,11 @@ _start:
   addi  gp, gp, %pcrel_lo(1b)
 .option pop
 
+  # Initialize table jump base
+2:auipc a0, %pcrel_hi(__tbljalvec_base$)
+  addi  a0, a0, %pcrel_lo(2b)
+  csrw tbljalvec, a0
+
   # Clear the bss segment
   la      a0, _edata
   la      a2, _end
```

**Comment by linsinan1995** [comment]
general info
```
sinan@sinan-Lenovo-Legion-7:~/plct/riscv-gnu-toolchain/mytest/tablejump$ ./../../obj-rv64gc_zcea/bin/riscv64-unknown-elf-readelf -a a.out
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           RISC-V
  Version:                           0x1
  Entry point address:               0x100c0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          10672 (bytes into file)
  Flags:                             0x5, RVC, double-float ABI
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         2
  Size of section headers:           64 (bytes)
  Number of section headers:         19
  Section header string table index: 18

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .text             PROGBITS         00000000000100b0  000000b0
       00000000000003f8  0000000000000000  AX       0     0     2
  [ 2] .tbljal           PROGBITS         00000000000104a8  000004a8
       0000000000000800  0000000000000000   A       0     0     1
  [ 3] .eh_frame         PROGBITS         0000000000011000  00001000
       0000000000000138  0000000000000000  WA       0     0     8
  [ 4] .init_array       INIT_ARRAY       0000000000011138  00001138
       0000000000000010  0000000000000008  WA       0     0     8
  [ 5] .fini_array       FINI_ARRAY       0000000000011148  00001148
       0000000000000008  0000000000000008  WA       0     0     8
  [ 6] .data             PROGBITS         0000000000011150  00001150
       0000000000000748  0000000000000000  WA       0     0     8
  [ 7] .sdata            PROGBITS         0000000000011898  00001898
       0000000000000018  0000000000000000  WA       0     0     8
  [ 8] .bss              NOBITS           00000000000118b0  000018b0
       0000000000000038  0000000000000000  WA       0     0     8
  [ 9] .comment          PROGBITS         0000000000000000  000018b0
       0000000000000012  0000000000000001  MS       0     0     1
  [10] .riscv.attributes RISCV_ATTRIBUTE  0000000000000000  000018c2
       0000000000000043  0000000000000000           0     0     1
  [11] .debug_aranges    PROGBITS         0000000000000000  00001910
       0000000000000030  0000000000000000           0     0     16
  [12] .debug_info       PROGBITS         0000000000000000  00001940
       000000000000002e  0000000000000000           0     0     1
  [13] .debug_abbrev     PROGBITS         0000000000000000  0000196e
       0000000000000014  0000000000000000           0     0     1
  [14] .debug_line       PROGBITS         0000000000000000  00001982
       00000000000001bc  0000000000000000           0     0     1
  [15] .debug_str        PROGBITS         0000000000000000  00001b3e
       000000000000009e  0000000000000001  MS       0     0     1
  [16] .symtab           SYMTAB           0000000000000000  00001be0
       00000000000008e8  0000000000000018          17    46     8
  [17] .strtab           STRTAB           0000000000000000  000024c8
       000000000000042c  0000000000000000           0     0     1
  [18] .shstrtab         STRTAB           0000000000000000  000028f4
       00000000000000b8  0000000000000000           0     0     1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  p (processor specific)

There are no section groups in this file.

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000010000 0x0000000000010000
                 0x0000000000000ca8 0x0000000000000ca8  R E    0x1000
  LOAD           0x0000000000001000 0x0000000000011000 0x0000000000011000
                 0x00000000000008b0 0x00000000000008e8  RW     0x1000

 Section to Segment mapping:
  Segment Sections...
   00     .text .tbljal 
   01     .eh_frame .init_array .fini_array .data .sdata .bss 

There is no dynamic section in this file.

There are no relocations in this file.

The decoding of unwind sections for machine type RISC-V is not currently supported.

Symbol table '.symtab' contains 95 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 00000000000100b0     0 SECTION LOCAL  DEFAULT    1 
     2: 00000000000104a8     0 SECTION LOCAL  DEFAULT    2 
     3: 0000000000011000     0 SECTION LOCAL  DEFAULT    3 
     4: 0000000000011138     0 SECTION LOCAL  DEFAULT    4 
     5: 0000000000011148     0 SECTION LOCAL  DEFAULT    5 
     6: 0000000000011150     0 SECTION LOCAL  DEFAULT    6 
     7: 0000000000011898     0 SECTION LOCAL  DEFAULT    7 
     8: 00000000000118b0     0 SECTION LOCAL  DEFAULT    8 
     9: 0000000000000000     0 SECTION LOCAL  DEFAULT    9 
    10: 0000000000000000     0 SECTION LOCAL  DEFAULT   10 
    11: 0000000000000000     0 SECTION LOCAL  DEFAULT   11 
    12: 0000000000000000     0 SECTION LOCAL  DEFAULT   12 
    13: 0000000000000000     0 SECTION LOCAL  DEFAULT   13 
    14: 0000000000000000     0 SECTION LOCAL  DEFAULT   14 
    15: 0000000000000000     0 SECTION LOCAL  DEFAULT   15 
    16: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS __call_atexit.c
    17: 00000000000100b0    16 FUNC    LOCAL  DEFAULT    1 register_fini
    18: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtstuff.c
    19: 0000000000011000     0 OBJECT  LOCAL  DEFAULT    3 __EH_FRAME_BEGIN__
    20: 0000000000010102     0 FUNC    LOCAL  DEFAULT    1 __do_global_dtors_aux
    21: 00000000000118b0     1 OBJECT  LOCAL  DEFAULT    8 completed.1
    22: 0000000000011148     0 OBJECT  LOCAL  DEFAULT    5 __do_global_dtor[...]
    23: 0000000000010134     0 FUNC    LOCAL  DEFAULT    1 frame_dummy
    24: 00000000000118b8    48 OBJECT  LOCAL  DEFAULT    8 object.0
    25: 0000000000011140     0 OBJECT  LOCAL  DEFAULT    4 __frame_dummy_in[...]
    26: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS test.c
    27: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS wow.c
    28: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS exit.c
    29: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS impure.c
    30: 0000000000011150  1864 OBJECT  LOCAL  DEFAULT    6 impure_data
    31: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS init.c
    32: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS fini.c
    33: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS atexit.c
    34: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS __atexit.c
    35: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS sys_exit.c
    36: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS errno.c
    37: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtstuff.c
    38: 0000000000011134     0 OBJECT  LOCAL  DEFAULT    3 __FRAME_END__
    39: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS 
    40: 0000000000011150     0 NOTYPE  LOCAL  DEFAULT    5 __fini_array_end
    41: 0000000000011148     0 NOTYPE  LOCAL  DEFAULT    5 __fini_array_start
    42: 0000000000011148     0 NOTYPE  LOCAL  DEFAULT    4 __init_array_end
    43: 0000000000011138     0 NOTYPE  LOCAL  DEFAULT    4 __preinit_array_end
    44: 0000000000011138     0 NOTYPE  LOCAL  DEFAULT    4 __init_array_start
    45: 0000000000011138     0 NOTYPE  LOCAL  DEFAULT    4 __preinit_array_start
    46: 0000000000011950     0 NOTYPE  GLOBAL DEFAULT  ABS __global_pointer$
    47: 0000000000010176    54 FUNC    GLOBAL HIDDEN     1 __riscv_save_8
    48: 00000000000101d0    14 FUNC    GLOBAL HIDDEN     1 __riscv_restore_3
    49: 00000000000101b8    38 FUNC    GLOBAL HIDDEN     1 __riscv_restore_10
    50: 000000000001016c    64 FUNC    GLOBAL HIDDEN     1 __riscv_save_11
    51: 00000000000104a2     6 FUNC    GLOBAL DEFAULT    1 __errno
    52: 0000000000011898     0 NOTYPE  GLOBAL DEFAULT    7 __SDATA_BEGIN__
    53: 00000000000101d0    14 FUNC    GLOBAL HIDDEN     1 __riscv_restore_2
    54: 0000000000010164    72 FUNC    GLOBAL HIDDEN     1 __riscv_save_12
    55: 00000000000118a0     0 OBJECT  GLOBAL HIDDEN     7 __dso_handle
    56: 00000000000101b8    38 FUNC    GLOBAL HIDDEN     1 __riscv_restore_11
    57: 00000000000101ac     8 FUNC    GLOBAL HIDDEN     1 __riscv_save_1
    58: 00000000000101d6     8 FUNC    GLOBAL HIDDEN     1 __riscv_restore_0
    59: 0000000000010180    44 FUNC    GLOBAL HIDDEN     1 __riscv_save_7
    60: 0000000000011898     8 OBJECT  GLOBAL DEFAULT    7 _global_impure_ptr
    61: 00000000000101ca    20 FUNC    GLOBAL HIDDEN     1 __riscv_restore_5
    62: 00000000000101f8   106 FUNC    GLOBAL DEFAULT    1 __libc_init_array
    63: 00000000000101c4    26 FUNC    GLOBAL HIDDEN     1 __riscv_restore_6
    64: 00000000000103ce    52 FUNC    GLOBAL DEFAULT    1 __libc_fini_array
    65: 0000000000010176    54 FUNC    GLOBAL HIDDEN     1 __riscv_save_9
    66: 0000000000010160     4 FUNC    GLOBAL DEFAULT    1 foo1
    67: 000000000001018c    32 FUNC    GLOBAL HIDDEN     1 __riscv_save_4
    68: 0000000000010198    20 FUNC    GLOBAL HIDDEN     1 __riscv_save_3
    69: 000000000001030c   194 FUNC    GLOBAL DEFAULT    1 __call_exitprocs
    70: 00000000000100c0    66 FUNC    GLOBAL DEFAULT    1 _start
    71: 000000000001040c   118 FUNC    GLOBAL DEFAULT    1 __register_exitproc
    72: 00000000000118e8     0 NOTYPE  GLOBAL DEFAULT    8 __BSS_END__
    73: 000000000001016c    64 FUNC    GLOBAL HIDDEN     1 __riscv_save_10
    74: 00000000000101ca    20 FUNC    GLOBAL HIDDEN     1 __riscv_restore_4
    75: 00000000000101be    32 FUNC    GLOBAL HIDDEN     1 __riscv_restore_8
    76: 0000000000010180    44 FUNC    GLOBAL HIDDEN     1 __riscv_save_6
    77: 00000000000118b0     0 NOTYPE  GLOBAL DEFAULT    8 __bss_start
    78: 0000000000010262   170 FUNC    GLOBAL DEFAULT    1 memset
    79: 00000000000101be    32 FUNC    GLOBAL HIDDEN     1 __riscv_restore_9
    80: 00000000000101c4    26 FUNC    GLOBAL HIDDEN     1 __riscv_restore_7
    81: 000000000001014e    18 FUNC    GLOBAL DEFAULT    1 main
    82: 00000000000104a8     0 NOTYPE  GLOBAL DEFAULT    2 __tbljalvec_base$
    83: 0000000000010402    10 FUNC    GLOBAL DEFAULT    1 atexit
    84: 00000000000118a8     8 OBJECT  GLOBAL DEFAULT    7 _impure_ptr
    85: 0000000000010198    20 FUNC    GLOBAL HIDDEN     1 __riscv_save_2
    86: 0000000000011150     0 NOTYPE  GLOBAL DEFAULT    6 __DATA_BEGIN__
    87: 000000000001018c    32 FUNC    GLOBAL HIDDEN     1 __riscv_save_5
    88: 00000000000118b0     0 NOTYPE  GLOBAL DEFAULT    7 _edata
    89: 00000000000118e8     0 NOTYPE  GLOBAL DEFAULT    8 _end
    90: 00000000000101de    26 FUNC    GLOBAL DEFAULT    1 exit
    91: 00000000000101b4    42 FUNC    GLOBAL HIDDEN     1 __riscv_restore_12
    92: 00000000000101ac     8 FUNC    GLOBAL HIDDEN     1 __riscv_save_0
    93: 0000000000010482    32 FUNC    GLOBAL DEFAULT    1 _exit
    94: 00000000000101d6     8 FUNC    GLOBAL HIDDEN     1 __riscv_restore_1

No version information found in this file.
Attribute Section: riscv
File Attributes
  Tag_RISCV_stack_align: 16-bytes
  Tag_RISCV_arch: "rv64i2p0_m2p0_a2p0_f2p0_d2p0_c2p0_zcea2p0"
  Tag_RISCV_priv_spec: 1
  Tag_RISCV_priv_spec_minor: 11
  Tag_RISCV_zce_tbljal: true
```
